### ISSUE TITLE
Can't access the login screen [locked-out]

### ISSUE THREAD

**Issue by gustavovalverde** [xubiuit/odoo_web_login#1]
After updating, now I can't access the login screen, so It's not possible to log in into the instance. We're getting an error from this line: 

` request.params['title'] = root_user.company_id and root_user.company_id.name or 'xubi.me'`

This is the log:
```
2017-03-18 12:21:09,794 958 ERROR demo werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/odoo/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 182, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/odoo/venv/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/odoo/venv/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/odoo/odoo-server/src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/src/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/custom/odoo_web_login/odoo_web_login/controllers/main.py", line 50, in web_login
    request.params['title'] = root_user.company_id and root_user.company_id.name or 'xubi.me'
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3064, in _prefetch_field
    result = self.read([f.name for f in fs], load='_classic_write')
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/res/res_users.py", line 856, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/res/res_users.py", line 297, in read
    result = super(Users, self).read(fields=fields, load=load)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3012, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5191, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 865, in __get__
    value = record._cache[self]
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5540, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 48, in get
    raise self.exception
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.users, Operation: read)', None)
```

**Comment by xubiuit** [comment]
Sorry for the inconvenience. Please remove that line in your code first. I will update new code shortly

**Comment by xubiuit** [comment]
@gustavovalverde hi, please checkout the newest version :)
