### ISSUE TITLE
Odoo 12 External ID not found in the system

### ISSUE THREAD

**Issue by dungxboss** [xubiuit/odoo_web_login#15]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/convert.py", line 269, in _tag_delete
    records = records.search(safe_eval(d_search, idref))
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/convert.py", line 27, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/convert.py", line 731, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/convert.py", line 737, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/base/models/ir_model.py", line 1361, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/base/models/ir_model.py", line 1350, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: website.login_layout" while evaluating
"[('id','=', ref('website.login_layout'))]"

Odoo 12.0-20181012 (Community Edition)

**Comment by xubiuit** [comment]
hi @dhamedic 
this is not an issue, please skip this since those lines will be used when you install module website.
