### ISSUE TITLE
[11.0] Erro install Skipping deletion for failed search `"[('id','=', ref('website.login_layout'))]"`

### ISSUE THREAD

**Issue by maiconkkl** [xubiuit/odoo_web_login#16]
2018-12-06 12:06:16,998 18289 WARNING vadinho odoo.tools.convert: Skipping deletion for failed search `"[('id','=', ref('website.login_layout'))]"`
Traceback (most recent call last):
  File "/opt/odoo/vadinho/core/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/vadinho/core/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/vadinho/core/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'vadinho'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/vadinho/core/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/vadinho/core/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/vadinho/core/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7ff4b025f730>, 'website.login_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/vadinho/core/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/vadinho/core/odoo/addons/base/ir/ir_model.py", line 1335, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/vadinho/core/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/vadinho/core/odoo/addons/base/ir/ir_model.py", line 1324, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: website.login_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 265, in _tag_delete
    records = records.search(safe_eval(d_search, idref))
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 28, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/opt/odoo/vadinho/core/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/vadinho/core/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/vadinho/core/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo/vadinho/core/odoo/tools/convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/vadinho/core/odoo/addons/base/ir/ir_model.py", line 1335, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/vadinho/core/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/vadinho/core/odoo/addons/base/ir/ir_model.py", line 1324, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: website.login_layout" while evaluating
"[('id','=', ref('website.login_layout'))]"

**Comment by xubiuit** [comment]
@maiconkkl 
don't worry about this issue, since we need to insert that line for any database which was installed module website, if you are not, then just ignore that message. It is only raised 1 time when you trying to install my module

**Comment by maiconkkl** [comment]
Thanks :)
