### ISSUE TITLE
not compatible with version 10

### ISSUE THREAD

**Issue by MosabHD** [xubiuit/odoo_web_login#2]
Hello xubiuit,
I tried to install the module to my odoo that is running on version 10 but this error appears:
Please solve this issue, I admire your work and wish to implement it on my odoo..

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 780, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1191, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 360, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3829, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 378, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3555, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3706, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<xpath expr="//t[@t-set='head']/link[last()]">' cannot be located in parent view

Error context:
View `Login Layout Inherit`
[view_id: 991, xml_id: n/a, model: n/a, parent_id: 165]
None" while parsing None:4, near
<data inherit_id="web.login_layout" name="Login Layout Inherit">
    		<xpath expr="//t[@t-set='body_classname']" position="replace">
    			<t t-set="body_classname" t-value="''"/>
    		</xpath>
    		
    		<xpath expr="//t[@t-set='head']/link[last()]" position="inside">
    			<link rel="stylesheet" href="/odoo_web_login/static/src/css/web_login_style.css"/>
    		</xpath>
    		
    		<xpath expr="//div[@class='row']" position="attributes">
    			<attribute name="class">body_login</attribute>
    		</xpath>
    		
    		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="before">
    			<div id="background-wrapper" t-attf-style="background-image: url('#{background_src}');"/>
    		</xpath>
    		
    		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="attributes">
    			<attribute name="class">col-lg-3 col-md-4 col-sm-4 col-xs-11 o_database_list</attribute>
    		</xpath>
    		
    		<xpath expr="//div[@class='text-center']/img" position="attributes">
    			<attribute name="class">company_logo</attribute>
    		</xpath>
    	</data>
```

**Comment by xubiuit** [comment]
Hi,
Sorry for this inconvenience. Please checkout the newest version.

Regard,

**Comment by MosabHD** [comment]
awesome, it installed.
But no images appears in the documentation or any thing

**Comment by IroniC0** [comment]
> Hola, disculpa este inconveniente. Consulte la versión más reciente.
> 
> Respecto,

Hola, tengo la version odoo community 14.0 ubuntu 20.04 y tengo el problema:
ningun error, y no sucede nada. imagenes etc... nada (cuando hago una inspeccion en el navegador, veo el url ('') vacio
Agradezco tu apoyo de ante mano
![url-vacio](https://user-images.githubusercontent.com/91710206/156101081-b8daa64b-a992-46eb-9b44-6bd1fc1a849f.jpeg)
