### ISSUE TITLE
Installation error Odoo 11

### ISSUE THREAD

**Issue by Vaerum** [xubiuit/odoo_web_login#8]
Hi
I am experiencing this error when trying to install the module in Odoo 11:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 316, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 700, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 649, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 627, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 489, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//t[@t-set='body_classname']">' cannot be located in parent view

Error context:
View `Login Layout Inherit`
[view_id: 1162, xml_id: n/a, model: n/a, parent_id: 159]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo11/odoo11-server/odoo/models.py", line 3285, in create
    self._fields[key].determine_inverse(record)
  File "/odoo11/odoo11-server/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo11/odoo11-server/odoo/models.py", line 3007, in write
    self._write(old_vals)
  File "/odoo11/odoo11-server/odoo/models.py", line 3160, in _write
    self._validate_fields(vals)
  File "/odoo11/odoo11-server/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//t[@t-set=\'body_classname\']">\' cannot be located in parent view\n\nError context:\nView `Login Layout Inherit`\n[view_id: 1162, xml_id: n/a, model: n/a, parent_id: 159]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo11/odoo11-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo11/odoo11-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo11/odoo11-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo11/odoo11-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo11/odoo11-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo11/odoo11-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo11/odoo11-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo11/odoo11-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo11/odoo11-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo11/odoo11-server/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo11/odoo11-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo11/odoo11-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo11/odoo11-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo11/odoo11-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo11/odoo11-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/odoo11/odoo11-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo11/odoo11-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo11/odoo11-server/odoo/models.py", line 3285, in create
    self._fields[key].determine_inverse(record)
  File "/odoo11/odoo11-server/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo11/odoo11-server/odoo/models.py", line 3007, in write
    self._write(old_vals)
  File "/odoo11/odoo11-server/odoo/models.py", line 3160, in _write
    self._validate_fields(vals)
  File "/odoo11/odoo11-server/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//t[@t-set='body_classname']">' cannot be located in parent view

Error context:
View `Login Layout Inherit`
[view_id: 1162, xml_id: n/a, model: n/a, parent_id: 159]
None" while parsing None:10, near
<data inherit_id="web.login_layout" name="Login Layout Inherit">
   		<xpath expr="//t[@t-set='body_classname']" position="replace">
   			<t t-set="body_classname" t-value="''"/>
   		</xpath>
   		
   		<xpath expr="//div[@class='row']" position="attributes">
   			<attribute name="class">body_login</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="before">
   			<div id="background-wrapper" t-attf-style="background-image: url('#{background_src}');"/>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="attributes">
   			<attribute name="class">col-lg-3 col-md-4 col-sm-4 col-xs-11 o_database_list</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='text-center']/img" position="attributes">
   			<attribute name="class">company_logo</attribute>
   		</xpath>
   	</data>
```

**Comment by xubiuit** [comment]
@Vaerum did you install another module which also customize login form?
My module only work for brand new database with no customization modules.

Let me know

**Comment by Vaerum** [comment]
It was a fresh install

**Comment by rwngallego** [comment]
I'm getting this same error. Is there any chance that the web login plugin is also compatible with Odoo 11?

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 333, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//t[@t-set='body_classname']">' no puede ser localizado en la vista padre

Contexto del error:
Vista `Login Layout Inherit`
[view_id: 1258, xml_id: n/a, model: n/a, parent_id: 178]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nEl elemento \'<xpath expr="//t[@t-set=\'body_classname\']">\' no puede ser localizado en la vista padre\n\nContexto del error:\nVista `Login Layout Inherit`\n[view_id: 1258, xml_id: n/a, model: n/a, parent_id: 178]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 927, in _call_
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

El elemento '<xpath expr="//t[@t-set='body_classname']">' no puede ser localizado en la vista padre

Contexto del error:
Vista `Login Layout Inherit`
[view_id: 1258, xml_id: n/a, model: n/a, parent_id: 178]
None" while parsing None:10, near
<data inherit_id="web.login_layout" name="Login Layout Inherit">
   		<xpath expr="//t[@t-set='body_classname']" position="replace">
   			<t t-set="body_classname" t-value="''"/>
   		</xpath>
   		
   		<xpath expr="//div[@class='row']" position="attributes">
   			<attribute name="class">body_login</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="before">
   			<div id="background-wrapper" t-attf-style="background-image: url('#{background_src}');"/>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="attributes">
   			<attribute name="class">col-lg-3 col-md-4 col-sm-4 col-xs-11 o_database_list</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='text-center']/img" position="attributes">
   			<attribute name="class">company_logo</attribute>
   		</xpath>
   	</data>
```

**Comment by xubiuit** [comment]
There is no issue with my module on the first install. I think there is any module which also inherit the "web.login_layout" template on your installed modules.
Please create a brand new database and try to install my module before install any others
In case it does not work again, please help me remove the line 11-13 in file `odoo_web_login/templates/webclient_templates.xml` and try to install again:

`<xpath expr="//t[@t-set='body_classname']" position="after">
<t t-set="body_classname" t-value="''"/>
</xpath>`

Let me know.

Regards,

**Comment by rwngallego** [comment]
Hi @xubiuit I have no additional third party modules installed. It's a Odoo 11 fresh installation (Odoo version: 11.0-20171218). I've removed what you suggested and now the lines 14-15 throw a similar error:

```
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//div[@class='row']">' cannot be located in parent view

Error context:
View `Login Layout Inherit`
[view_id: 1275, xml_id: n/a, model: n/a, parent_id: 178]
None" while parsing None:10, near
<data inherit_id="web.login_layout" name="Login Layout Inherit">
<!--   		<xpath expr="//t[@t-set='body_classname']" position="replace">
   			<t t-set="body_classname" t-value="''"/>
   		</xpath>-->
   		
   		<xpath expr="//div[@class='row']" position="attributes">
   			<attribute name="class">body_login</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="before">
   			<div id="background-wrapper" t-attf-style="background-image: url('#{background_src}');"/>
   		</xpath>
   		
   		<xpath expr="//div[@class='col-md-6 col-md-offset-3 o_database_list']" position="attributes">
   			<attribute name="class">col-lg-3 col-md-4 col-sm-4 col-xs-11 o_database_list</attribute>
   		</xpath>
   		
   		<xpath expr="//div[@class='text-center']/img" position="attributes">
   			<attribute name="class">company_logo</attribute>
   		</xpath>
   	</data>
```

**Comment by xubiuit** [comment]
@rwngallego can you try to get the latest source code from Odoo and my web_login module as I saw there are old modules (source code)

**Comment by rwngallego** [comment]
Same error. I've downloaded the latest version of your project from Github, branch 11. It's not possible to upgrade Odoo, however it's version 11 and others could have that same error.

**Comment by rwngallego** [comment]
Hello @xubiuit I've finally updated Odoo from version 11.0-20171218 to 11.0-20180218 and the problem has disappeared.

**Comment by xubiuit** [comment]
@rwngallego there is an issue if you install my module with website module native, please update newest source code
